
# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macOS-latest
            rversion: "4.0"
            bspm: "true"
          - os: ubuntu-latest
            rversion: "4.0"
            bspm: "true"
          - os: ubuntu-16.04
            rversion: "3.5"
            bspm: "false"

    runs-on: ${{ matrix.os }}
    
    env:
      USE_BSPM: ${{ matrix.bspm }}
      _R_CHECK_FORCE_SUGGESTS_: "false"
      COVERAGE_TYPE: "all"
      R_VERSION: ${{ matrix.rversion }}

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        run: |
          curl -OLs https://raw.githubusercontent.com/rubak/r-ci/master/docs/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap

      - name: Dependencies
        run: ./run.sh install_all

      - name: Test
        run: ./run.sh run_tests

      - name: Coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./run.sh coverage
